### ISSUE TITLE
Simplify deployment by removing the Ansible job

### ISSUE THREAD

**Issue by bbrowning** [apache/incubator-openwhisk-deploy-kube#10]
Deployment on Kubernetes today creates a Kubernetes job that runs Ansible playbooks to then create the other Kubernetes resources. It would be great to simplify this so that a user can just `kubectl create -f deploy_openwhisk.yml` to deploy an entire working OpenWhisk system directly versus deploying a Job that then deploys the other pieces.

This will require pulling all configuration out of Ansible into ConfigMaps or something similar that Kubernetes can use. And the CouchDB and Kafka image start scripts or the images themselves will need to be changed to create the necessary Kafka topics and CouchDB config changes since Ansible won't be running to do this after the images boot.

**Comment by mrutkows** [comment]
@bbrowning That is the eventual goal... Ansible may be used as an optional (common) launching point so that all deployments could start from the same place... @DanLavine is working on outlining more discrete epics/issues to get us there which he plans to post and discuss on the Apache "dev" list once he gets them sorted out.

**Comment by bbrowning** [comment]
Using Ansible to generate the Kubernetes yml files would keep all the configuration in Ansible while also allowing simplified deployment from those generated files. @tobias and I are prototyping a simple Kubernetes-only deployment now just to better understand the scope of the changes required long-term and will join in on the dev discussion.

**Comment by DanLavine** [comment]
hey @bbrowning, I totally agree with you. This was kind of a first step on what it currently takes to get OpenWhisk on Kube and get an Idea of what features we would like so that all of the components can be built into a service/deployment yaml. We just created a document in the OpenWhisk [wiki](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=70258567) as a proposal to the issues we encountered when doing this work. It would be great to get some feedback or any suggests from the community to help drive this forward.

**Comment by bbrowning** [comment]
We have a proof-of-concept of this you can try with the instructions at https://github.com/projectodd/incubator-openwhisk-deploy-kube/blob/simplify-deployment/README_CONSOLIDATED.md . It's just something hacked together to see what's possible and still runs some of the Ansible scripts (initdb, wipe, postDeploy) during startup of the appropriate pods.

**Comment by dgrove-oss** [comment]
I believe this issue can be closed as completed.
