### ISSUE TITLE
issue with invoker

### ISSUE THREAD

**Issue by mimizone** [apache/incubator-openwhisk-deploy-kube#12]
when trying to deploy, I run into this issue with the invoker.
```
Failed to start container with id 8d9125bf2d3711312a98a8b98de15306e495883cc470a03beb6689b34895791f with error: rpc error: code = 2 desc = failed to start container "8d9125bf2d3711312a98a8b98de15306e495883cc470a03beb6689b34895791f": Error response from daemon: {"message":"mkdir /usr/lib/x86_64-linux-gnu: read-only file system"}
Error syncing pod, skipping: failed to "StartContainer" for "invoker" with rpc error: code = 2 desc = failed to start container "8d9125bf2d3711312a98a8b98de15306e495883cc470a03beb6689b34895791f": Error response from daemon: {"message":"mkdir /usr/lib/x86_64-linux-gnu: read-only file system"}: "Start Container Failed"
```

on the logs of the pod in k8s I see the following
```
failed to open log file "/var/log/pods/7fce67a4-4d69-11e7-a736-0242ac110003/invoker_41.log": open /var/log/pods/7fce67a4-4d69-11e7-a736-0242ac110003/invoker_41.log: no such file or directory
```

I checked if the host drive was filling up, but everything is all good there.

I run k8s 1.6.2 on CoreOs 1353.7.
I edited the `configure_whisk.yml` to use the 1.6.2 version.
```
      - name: configure-openwhisk
        image: danlavine/whisk_config:v1.6.2
        imagePullPolicy: Always
```

I tried 3 times the deployment with the same result.

**Comment by bbrowning** [comment]
On Slack, it was suggested to try removing the `/usr/lib/x86_64-linux-gnu/libapparmor.so.1` mount from the invoker.yml as that is an Ubuntu-specific path. Docker is trying to create this non-existent path on the host and failing because it doesn't have sufficient permissions to do so. In your case, you can probably remove the apparmor volume and volumemount entries completely.

While in there, you should review all the mounts and ensure they match the paths on CoreOs. You can test these changes quickly by editing  https://github.com/apache/incubator-openwhisk-deploy-kube/blob/910f7b808a39e91aedff064f444f453f1da1c8c4/ansible-kube/environments/kube/files/invoker.yml to update the paths and then deleting (`kubectl delete statefulset/invoker`) and re-creating (`kubectl create -f /path/to/edited/invoker.yml`) the Invoker.

**Comment by DanLavine** [comment]
hey @mimizone I updated the PR to include a troubleshooting section for issues like this. Would that be able to close this PR or do you think that there is something else missing?

**Comment by mimizone** [comment]
@DanLavine I commented all the lines related to apparmor in the invoker as you suggested.
https://github.com/mimizone/incubator-openwhisk-deploy-kube/commit/fc53714adb608376952e62e568b3de7971a108ea

It seems to do the trick!

**Comment by dgrove-oss** [comment]
I think this PR can be closed.  Can someone with the ability to do that please take care of it?
