### ISSUE TITLE
Where should the <domain> come from for GKE nginx ingress?

### ISSUE THREAD

**Issue by nerdguru** [apache/incubator-openwhisk-deploy-kube#258]
On the new instructions for Google ingress:

https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/ingress.md

Where should the <domain> come from?  When you deploy a standard GKE cluster, you get an IP address of the master node, but not a domain.  Or am I misreading something?

**Comment by cduque89** [comment]
Hi @nerdguru.

You are the one defining the domain in your google cloud.

Please give a look into:
https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip

Hope this helps.

**Comment by nerdguru** [comment]
Hi Carlos and thanks for the quick reply.  So does that imply that a domain name for my GKE cluster is required for OpenWhisk?  For development situations where I may be bringing K8S clusters up and down frequently, being able to use an IP address would be more convenient.  Or am I missing something?

**Comment by cduque89** [comment]
Hi @nerdguru.

If that's the case you can still have your DNS domain as described in the documentation link and use it in different K8s clusters. 
Or you might decide to configure it just with a static external-ip as described in the previous section of the docs: https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer maybe it suites you best. 
We never used this approach since we find it easier with the first one. 
Not that even with the situation of bringing K8s clusters up and down frequently you can keep the same gcloud domains since it's an independent resource in your gcloud account.

**Comment by dgrove-oss** [comment]
Merged #259
