### ISSUE TITLE
enable replicated kafka pods

### ISSUE THREAD

**Issue by dgrove-oss** [apache/incubator-openwhisk-deploy-kube#354]
For production deployments, the kakfa StatefulSet should have a replicaCount > 1.

To enable this, we need to do similar changes as we did to enable replicated zookeeper.
  1. Change the PVC to a PVCTemplate
  2. Need a kakfa-connect macro in _helpers so that clients can be told about the multiple kafka brokers they should connect to.

**Comment by JiniousChoi** [comment]
You said at #446 that

> A better approach (and what is done in production deployments of OpenWhisk on Kubernetes for IBM Cloud Functions) is to deploy a replicated Kafka within the same Kubernetes cluster as the rest of the OpenWhisk control plane.

You mean the Kafka on 'Openwhisk on k8s for IBM Cloud Functions' is replicated >1, which mean multiple pods of kafkas, and it's on a roll, right?

If so, did you do something like, you created PVC's for kafkas as many you think you need for the service as manually, launch a stateful kafka service manually, and you also modified the dockers' env.s for the replicated controllers/invokers so that they can connect to the kafkas?

And now, we need to modify the Helm chart so that it can automatically create PVs/PVCs, deploy replicated kafkas >=1 on the same node as zookeepers?
