### ISSUE TITLE
A tutorial for deploying openwhisk on kube without using helm

### ISSUE THREAD

**Issue by ZhuozhaoLi** [apache/incubator-openwhisk-deploy-kube#443]
Hi, do you have a tutorial for deploying openwhisk on kube without using helm?

This is useful because we have a kubernetes cluster with limited privilege -- we cannot deploy tiller on kube-system namespace. Thanks.

**Comment by dgrove-oss** [comment]
I think it could work to use `helm template` to render the yaml and then `kubectl apply` on the yaml.

Instead of 
`helm install ./helm/openwhisk --namespace=openwhisk --name=owdev -f mycluster.yaml`
do 
```
helm template ./helm/openwhisk --namespace=openwhisk --name=owdev -f mycluster.yaml > tmp.yaml
kubectl apply -f tmp.yaml
```

**Comment by ZhuozhaoLi** [comment]
Thanks for the response. The problem is that I do not have cluster-admin role on the kubernetes cluster, which disallows me to run `kubectl create clusterrolebinding tiller-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default`. 

I want to confirm: can we run openwhisk on a kubernetes cluster without cluster-admin role?

> I think it could work to use `helm template` to render the yaml and then `kubectl apply` on the yaml.
> 
> Instead of
> `helm install ./helm/openwhisk --namespace=openwhisk --name=owdev -f mycluster.yaml`
> do
> 
> ```
> helm template ./helm/openwhisk --namespace=openwhisk --name=owdev -f mycluster.yaml > tmp.yaml
> kubectl apply -f tmp.yaml
> ```

**Comment by dgrove-oss** [comment]
You'll need some level of privilege to deploy OpenWhisk on Kubernetes because the OpenWhisk invokers need to be able to create additional containers to execute the user's functions. 

When using the DockerContainerFactory, this is done by mounting several Docker-related volumes via hostPath mounts into the invoker container (see https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/templates/_invoker-helpers.tpl#L5-#L21)

When using the KubernetesContainerFactory, this is done by giving the Invoker Pod increased privileges so it can create pods itself (see https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/templates/invoker-role.yaml).

**Comment by dgrove-oss** [comment]
Closing as I don't think we can support deploying OpenWhisk onto a cluster where the user deploying OpenWhisk does not have at least some admin capabilities as noted in my previous comment.
