### ISSUE TITLE
Add support for external Kafka as an option

### ISSUE THREAD

**Issue by JiniousChoi** [apache/incubator-openwhisk-deploy-kube#446]
I don't see any configurable option for `Kafka as a Service` on the project.
I found the external option for DB useful and I think it would be the same for Kafka.

Aside from #354 supporting an external option for Kafka would let each Openwhisk admin utilize their own Kafka's if they have any.

I heard from @csantanapr that IBM manages its fully-managed Openwhisk on k8s and almost all part, of which replicaCounts are fixed by 1, such as Nginx, Kafka, Zookeeper, etc, is powered by `as a Service` components, dogfooding. (https://openwhisk-team.slack.com/archives/C3UDXSFA6/p1552542936164000)

As far as I understand one cannot help but modify the project's helm chart to use external `Kafka as a Service` at the moment. Will I meet the external Kafka option later on new commits, or am I on my own for the time being?

I am intended to contribute for that matter if you find it useful and if you need a hand.

**Comment by JiniousChoi** [comment]
Just so you know, I'd love to abandon ansible script and migrate to k8s cluster for further Openwhisk devops. But as you know `incubator-openwhisk-deploy-kube` is far from production-ready out-of-the-box at the moment.  I see only one option - take the full advantages of SaaS for almost all components but controllers and invokers. And I'd love to start with Kafka first

**Comment by dgrove-oss** [comment]
Hi.  External Kafka is probably a questionable choice because Kakfa is on the critical path (between the Controller and Invoker).  A better approach (and what is done in production deployments of OpenWhisk on Kubernetes for IBM Cloud Functions) is to deploy a replicated Kafka within the same Kubernetes cluster as the rest of the OpenWhisk control plane.

External database is sensible for production (and the Helm chart does support that already).

It would be better to work on extending the chart to support replicated Kafka.

**Comment by dgrove-oss** [comment]
Also note the Helm chart already supports replicated Zookeeper and that replicated nginx is less pressing because in production one uses the Kubernetes ingress for most traffic, not the nginx pod that gets deployed by the Helm chart.  See https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/templates/frontdoor-ingress.yaml#L25-#L50.

**Comment by JiniousChoi** [comment]
Hi back. Thanks for the explanation. 
I am convinced. Let's talk further for replicated Kafka on #354

**Comment by JiniousChoi** [comment]
For Nginx, by the way, then, are we going to deprecate/remove the Nginx pod that gets deployed by the Helm chart later?

**Comment by dgrove-oss** [comment]
Hi.  Even with the ingress enabled, there are some secondary routes that get sent to the nginx pod.  Perhaps we should stop supporting these routes, but for now we are directing them to the nginx pod/service in the ingress.  

This part of nginx.conf is used https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/templates/nginx-cm.yaml#L95-#L130
and is targeted by the last rule in the ingress here https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/templates/frontdoor-ingress.yaml#L51-#L54

**Comment by dgrove-oss** [comment]
Since I made some progress on #354 with #451 I am going to close this issue.
